"""
Configuration management for YNAB CLI.

Handles configuration from multiple sources:
1. Environment variables (YNAB_API_TOKEN, YNAB_BUDGET_ID)
2. .env file in current directory or project root
3. Config file at ~/.config/ynab/config.toml
4. Defaults (budget_id = 'last-used')

Priority: Environment variables > .env file > Config file > Defaults
"""

import os
import tomllib
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

# Load .env file if it exists
# This must happen at module import time to populate os.environ
# before Settings instances are created
load_dotenv()


class Settings:
    """
    YNAB CLI settings manager.

    Reads configuration from (in priority order):
    1. Environment variables (YNAB_API_TOKEN, YNAB_BUDGET_ID)
    2. .env file in current directory or project root (auto-loaded)
    3. Config file at ~/.config/ynab/config.toml
    4. Defaults (budget_id = 'last-used')

    Note: .env files are loaded automatically when this module is imported.
    Environment variables from .env files are treated the same as system env vars.
    """

    def __init__(self) -> None:
        """Initialize settings."""
        self._config_cache: dict[str, Any] | None = None

    @property
    def config_dir(self) -> Path:
        """Get config directory path (~/.config/ynab)."""
        return Path.home() / ".config" / "ynab"

    @property
    def config_file(self) -> Path:
        """Get config file path (~/.config/ynab/config.toml)."""
        return self.config_dir / "config.toml"

    def _read_config_file(self) -> dict[str, Any]:
        """
        Read and parse the TOML config file.

        Returns:
            Dictionary of config values, or empty dict if file doesn't exist or is invalid.
        """
        if self._config_cache is not None:
            return self._config_cache

        if not self.config_file.exists():
            self._config_cache = {}
            return self._config_cache

        try:
            with self.config_file.open("rb") as f:
                self._config_cache = tomllib.load(f)
            return self._config_cache
        except (tomllib.TOMLDecodeError, OSError):
            # Handle malformed TOML or file read errors gracefully
            self._config_cache = {}
            return self._config_cache

    @property
    def api_token(self) -> str | None:
        """
        Get API token.

        Priority:
        1. YNAB_API_TOKEN environment variable (includes .env file)
        2. api_token from config file (~/.config/ynab/config.toml)
        3. None

        Returns:
            API token string or None if not configured.
        """
        # Priority 1: Environment variable
        env_token = os.environ.get("YNAB_API_TOKEN")
        if env_token:
            return env_token

        # Priority 2: Config file
        config = self._read_config_file()
        return config.get("api_token")

    @property
    def budget_id(self) -> str:
        """
        Get budget ID.

        Priority:
        1. YNAB_BUDGET_ID environment variable (includes .env file)
        2. budget_id from config file (~/.config/ynab/config.toml)
        3. 'last-used' (default)

        Returns:
            Budget ID string (defaults to 'last-used').
        """
        # Priority 1: Environment variable
        env_budget = os.environ.get("YNAB_BUDGET_ID")
        if env_budget:
            return env_budget

        # Priority 2: Config file
        config = self._read_config_file()
        file_budget = config.get("budget_id")
        if file_budget:
            return str(file_budget)

        # Priority 3: Default
        return "last-used"

    def save_token(self, token: str, budget_id: str) -> None:
        """
        Save API token and budget ID to config file.

        Creates ~/.config/ynab directory if it doesn't exist.
        Sets file permissions to 0o600 (user read/write only).

        Args:
            token: YNAB API token
            budget_id: Budget ID (or 'last-used', 'default')
        """
        # Create config directory if it doesn't exist
        self.config_dir.mkdir(parents=True, exist_ok=True)

        # Write TOML config file
        config_content = f"""# YNAB CLI Configuration
# Generated by 'ynab login' command

api_token = "{token}"
budget_id = "{budget_id}"
"""

        self.config_file.write_text(config_content)

        # Set secure permissions (user read/write only)
        self.config_file.chmod(0o600)

        # Clear cache so next read gets new values
        self._config_cache = None


# Global settings instance
settings = Settings()
